<a href="https://colab.research.google.com/github/mdzubayereashraf/Pandas/blob/main/Data_Manipulation_with_pandas(Students_Exam_Scores).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Students Exam Scores Dataset Manipulation With Pandas**

In [1]:
import pandas as pd

## **Loading The dataset**

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Kaggle Datasets/Students Exam Scores/Original_data_with_more_rows.csv')
df.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75

## **Checking Details**

In [3]:
df.shape

(30641, 9)

In [4]:
df.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'MathScore', 'ReadingScore', 'WritingScore'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    30641 non-null  int64
 1   Gender        30641 non-null  object
 2   EthnicGroup   30641 non-null  object
 3   ParentEduc    30641 non-null  object
 4   LunchType     30641 non-null  object
 5   TestPrep      30641 non-null  object
 6   MathScore     30641 non-null  int64
 7   ReadingScore  30641 non-null  int64
 8   WritingScore  30641 non-null  int64
dtypes: int64(4), object(5)
memory usage: 2.1+ MB

## **Checking Missing Values**

In [6]:
df.isnull().sum()

Unnamed: 0      0
Gender          0
EthnicGroup     0
ParentEduc      0
LunchType       0
TestPrep        0
MathScore       0
ReadingScore    0
WritingScore    0
dtype: int64

In [7]:
df.isnull().mean() * 100

Unnamed: 0      0.0
Gender          0.0
EthnicGroup     0.0
ParentEduc      0.0
LunchType       0.0
TestPrep        0.0
MathScore       0.0
ReadingScore    0.0
WritingScore    0.0
dtype: float64

## **Deleting Redundant Columns**

In [8]:
df.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'MathScore', 'ReadingScore', 'WritingScore'],
      dtype='object')

In [9]:
drop_columns = ['Unnamed: 0', 'EthnicGroup', 'LunchType']

In [14]:
df.drop(columns = drop_columns,inplace = True , errors= 'ignore')
df

,Gender,ParentEduc,TestPrep,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [15]:
df.shape

(30641, 6)

## **Renaming The Columns**

In [26]:
df.rename(columns = {"ParentEduc": "ParentEducation", "TestPrep": "TestPreparation" }, inplace= True) # you must put the argument inplace otherwise it won't change the columns name
df

,Gender,ParentEducation,TestPreparation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66