<a href="https://colab.research.google.com/github/mdzubayereashraf/Pandas/blob/main/Data_Structure(Series%2C_Dataframe)_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introduction**

Pandas is a Python library built on top of NumPy, designed to work with structured data like tables and spreadsheets. Just like NumPy gave us powerful arrays, Pandas gives us powerful tables called DataFrames.

**`What is Pandas?`**

Pandas = Panel Data. It lets you load, clean, filter, and analyze data in rows and columns just like Excel, but with Python code.

**`Import Pandas`**

We always import pandas as pd this is a universal convention in the Python world.

## **`Series - 1D Data`**

A Series is like a single column of a table a list of values with labels called index. Think of it as a NumPy array with named rows.

**`Creating a Series from a list`**

In [ ]:
import pandas as pd

scores = pd.Series([34, 53, 24, 42, 25, 13, 35, 16 ,45])
scores

0    34
1    53
2    24
3    42
4    25
5    13
6    35
7    16
8    45
dtype: int64

In [ ]:
scores = pd.Series([34, 53, 24, 42, 25, 13, 35, 16 ,45], name ="Numbers")
scores

0    34
1    53
2    24
3    42
4    25
5    13
6    35
7    16
8    45
Name: Numbers, dtype: int64

## **`Series with custom index`**

In [ ]:
scores = pd.Series([34, 53, 24, 42, 25, 13, 35, 16 ,45], name = " Numbers", index = [1,2,3,4,5,6,7,8,9])
scores

1    34
2    53
3    24
4    42
5    25
6    13
7    35
8    16
9    45
Name:  Numbers, dtype: int64

In [ ]:
scores = pd.Series([34, 53, 24, 42, 25, 13, 35, 16 ,45],
                   name = " Numbers", index = ["Taki", "Yamin", "Ashraf", "Abir", "Akash"," Palak", "Pakhi", "Rahat", "Faruk"])
scores

Taki      34
Yamin     53
Ashraf    24
Abir      42
Akash     25
 Palak    13
Pakhi     35
Rahat     16
Faruk     45
Name:  Numbers, dtype: int64

## **`Series from a dictionary`**

In [ ]:
dic = {
    "Rafi" : 45,
    "Kafi" : 65,
    "Naim" : 75,
    "Raki" : 45
}
scores = pd.Series(dic, name = "Numbers")
scores

Rafi    45
Kafi    65
Naim    75
Raki    45
Name: Numbers, dtype: int64

## **`DataFrame - 2D Table`**

A DataFrame is the heart of Pandas. It is a table with rows and columns they form a DataFrame. exactly like a spreadsheet. Each column is a Series, and together

## **`Creating a DataFrame from a dictionary`**

In [ ]:
dic = {
    "Name" : ["Rahat","Taha", "Abrar", "Sufian", "Emty"],
    "Age" : [ 23, 34, 32, 21, 12],
    "Scores" : [45, 35, 52, 23, 54]
}
df = pd.DataFrame(dic)
df

     Name  Age  Scores
0   Rahat   23      45
1    Taha   34      35
2   Abrar   32      52
3  Sufian   21      23
4    Emty   12      54

## **`Explore the DataFrame`**

In [ ]:
dic = {
    "Name" : ["Rahat","Taha", "Abrar", "Sufian", "Emty"],
    "Age" : [ 23, 34, 32, 21, 12],
    "Scores" : [45, 35, 52, 23, 54]
}
df = pd.DataFrame(dic)

print(df.shape)
print(df.dtypes)
print(df.size)

(5, 3)
Name      object
Age        int64
Scores     int64
dtype: object
15
    Name  Age  Scores
0  Rahat   23      45
1   Taha   34      35
     Name  Age  Scores
3  Sufian   21      23
4    Emty   12      54

In [ ]:
dic = {
    "Name" : ["Rahat","Taha", "Abrar", "Sufian", "Emty"],
    "Age" : [ 23, 34, 32, 21, 12],
    "Scores" : [45, 35, 52, 23, 54]
}
df = pd.DataFrame(dic)

print(df.head(2))
print(df.tail(2))

    Name  Age  Scores
0  Rahat   23      45
1   Taha   34      35
     Name  Age  Scores
3  Sufian   21      23
4    Emty   12      54