<a href="https://colab.research.google.com/github/mdzubayereashraf/Pandas/blob/main/Groupby_%2CConcatination%2C_Merging_%26_Joining_DataFrames_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Groupby & Aggregation**

GroupBy is one of the most powerful features in Pandas. It groups rows that share a value, then lets you calculate statistics per group - just

like a Pivot Table in Excel.

1. Basic GroupBy

2. Multiple aggregations with agg()

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Titinic /titanic.csv")

## **1. Basic GroupBy**

## We can calculate statistical measurement by categorical data's group.

In [ ]:
mean_of_every_sex_group = df.groupby('Sex')['Age'].mean()
mean_of_every_sex_group

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [ ]:
median_of_every_sex_group = df.groupby('Sex')['Age'].median()
median_of_every_sex_group

Sex
female    27.0
male      29.0
Name: Age, dtype: float64

In [ ]:
std_of_every_sex_group = df.groupby('Sex')['Age'].std()
std_of_every_sex_group

Sex
female    14.110146
male      14.678201
Name: Age, dtype: float64

## **2. Multiple aggregations with agg()**

In [ ]:
Multiple_Measurement = df.groupby('Sex')['Age'].agg(["mean", "median", "max", "count"])
Multiple_Measurement

             mean  median   max  count
Sex
female  27.915709    27.0  63.0    261
male    30.726645    29.0  80.0    453

In [ ]:
Multiple_Measurement = df.groupby('Embarked')['Age'].agg(["mean", "median", "max", "count"])
Multiple_Measurement

               mean  median   max  count
Embarked
C         30.814769    29.0  71.0    130
Q         28.089286    27.0  70.5     28
S         29.445397    28.0  80.0    554

## **Merging & Joining DataFrames**
Real projects have data spread across multiple tables. Merging combines two DataFrames using a common column - just like JOIN in SQL or VLOOKUP in Excel.

1. Inner join - keep only matches

2. Left join - keep all left rows

3. Right join - keep all Right rows
## `inner join`
pd.merge(df1, df2, on='id', how='inner')
## `left join`
pd.merge(df1, df2, on='id', how='left')
## `right join`
pd.merge(df1, df2, on='id', how='right')
## `outer join`
pd.merge(df1, df2, on='id', how='outer')

In [ ]:
df1 = pd.DataFrame( {
    "Name" : ["Rahat","Taha", "Abrar", "Sufian", "Emty"],
    "Age" : [ 23, 34, 32, 21, 12],
    "Scores" : [45, 35, 52, 23, 54]})
df2 = pd.DataFrame( {
    "Name" : ["Kawser","Sujon", "Babu", "Pias", "Faruk"],
    "Age" : [ 25, 37, 38, 29, 19],
    "Scores" : [55, 45, 72, 33, 84]})

display(df1) # to show dataframe as a table

print(df1)

     Name  Age  Scores
0   Rahat   23      45
1    Taha   34      35
2   Abrar   32      52
3  Sufian   21      23
4    Emty   12      54

     Name  Age  Scores
0   Rahat   23      45
1    Taha   34      35
2   Abrar   32      52
3  Sufian   21      23
4    Emty   12      54

## `inner join`

In [ ]:
pd.merge(df1, df2,  how = "inner")

Empty DataFrame
Columns: [Name, Age, Scores]
Index: []

## `left join`

In [ ]:
pd.merge(df1, df2, on = "Name", how = "left")

     Name  Age_x  Scores_x  Age_y  Scores_y
0   Rahat     23        45    NaN       NaN
1    Taha     34        35    NaN       NaN
2   Abrar     32        52    NaN       NaN
3  Sufian     21        23    NaN       NaN
4    Emty     12        54    NaN       NaN

In [ ]:
pd.merge(df1, df2,  how = "left")

     Name  Age  Scores
0   Rahat   23      45
1    Taha   34      35
2   Abrar   32      52
3  Sufian   21      23
4    Emty   12      54

## `right join`

In [ ]:
pd.merge(df1, df2,  how = "right")

     Name  Age  Scores
0  Kawser   25      55
1   Sujon   37      45
2    Babu   38      72
3    Pias   29      33
4   Faruk   19      84

## `outer join`

In [ ]:
pd.merge(df1, df2,  how = "outer")

     Name  Age  Scores
0   Abrar   32      52
1    Babu   38      72
2    Emty   12      54
3   Faruk   19      84
4  Kawser   25      55
5    Pias   29      33
6   Rahat   23      45
7  Sufian   21      23
8   Sujon   37      45
9    Taha   34      35

# **CONCATENATION**
1. pd.concat([df1, df2]) # row wise
2. pd.concat([df1, df2], axis=1) # col wise

In [ ]:
pd.concat([df1, df2]) # row wise

     Name  Age  Scores
0   Rahat   23      45
1    Taha   34      35
2   Abrar   32      52
3  Sufian   21      23
4    Emty   12      54
0  Kawser   25      55
1   Sujon   37      45
2    Babu   38      72
3    Pias   29      33
4   Faruk   19      84

In [ ]:
pd.concat([df1, df2], axis=1) # col wise

     Name  Age  Scores    Name  Age  Scores
0   Rahat   23      45  Kawser   25      55
1    Taha   34      35   Sujon   37      45
2   Abrar   32      52    Babu   38      72
3  Sufian   21      23    Pias   29      33
4    Emty   12      54   Faruk   19      84